# Generated by Django 5.2.4 on 2025-08-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_coolie_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='chepak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email_address', models.CharField(max_length=100)),
                ('Password', models.TextField()),
                ('Confirm_Password', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coolie',
            name='Password',
            field=models.IntegerField(),
        ),
    ]
