# Generated by Django 5.2.4 on 2025-08-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_chepak_alter_coolie_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email_address', models.CharField(max_length=100)),
                ('Password', models.TextField()),
                ('Confirm_Password', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='chepak',
        ),
        migrations.DeleteModel(
            name='coolie',
        ),
    ]
