# Generated by Django 5.2.4 on 2025-08-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
